sweep_prefix: "one_cycle_b64"

method: bayes
metric:
  name: val_total_loss
  goal: minimize

num_epochs: 2

parameters:
  num_epochs:
    value: 15

  model_type:
    value: "mobilenet_v3_small"
  ds_path:
    value: "dataset/folds/fold_0"
  #    value: "dataset/fold_0_1_2_4_8"

  batch_size:
    value: 64
  freeze_epochs:
    values: [ 0, 1, 2, 3 ]
  gender_loss_weight:
    value: 0.9

  # optimizer
  base_lr:
    distribution: uniform
    min: 0.0001
    max: 0.005
  weight_decay:
    distribution: uniform
    min: 0.0001
    max: 0.002
  #
  #
  # reg
  dropout:
    values: [ 0.0, 0.1, 0.2, 0.3 ]
  l1_lambda:
    values: [ 0.000001, 0.00001, 0.0001 ]
  #
  #scheduler
  lr_scheduler:
    value: "one_cycle"

  max_lr:
    distribution: uniform
    #    min: 0.01
    #    max: 0.1
    min: 0.005
    max: 0.05

  anneal_strategy:
    value: "cos"

  pct_start:
    distribution: uniform
    min: 0.15
    max: 0.35
  div_factor:
    distribution: int_uniform
    min: 15
    max: 25
  final_div_factor:
    distribution: int_uniform
    min: 1000
    max: 15000
  #
  # Transforms
  include_random_grayscale:
    value: true
  include_random_perspective:
    value: true
  include_random_erasing:
    value: true
  include_random_rotation:
    values: [ True, False ]
  include_center_crop:
    values: [ True, False ]
  include_random_horizontal_flip:
    values: [ True, False ]
  include_color_jitter:
    value: true
  include_random_affine:
    value: false
  include_gaussian_blur:
    value: false
  include_gaussian_noise:
    value: false

count: 100