# Optimized based on tuning for individual schedulers/etc,
#
#
sweep_prefix: "optimized_v2"
method: bayes
metric:
  name: val_total_loss
  goal: minimize

num_epochs: 20

parameters:
  model_type:
    value: "mobilenet_v3_small"
  ds_path:
    #    value: "dataset/folds/fold_0"
    value: "dataset/fold_0_1_2_4_8"

  # Pre:
  dropout:
    values: [ 0, 0.1, 0.15, 0.2, 0.25 ]


  #OPTIMIZER
  # TODO, fix or decrease range
  weight_decay:
    distribution: uniform
    min: 0.005
    max: 0.05

  base_lr:
    distribution: uniform
    min: 0.01
    max: 0.1
  # - - -


  # Scheduler specific
  # TODO is plateu really best? Check.
  lr_scheduler:
    values: [ reduce_on_plateau ]

  threshold:
    distribution: uniform
    min: 0.0
    max: 0.15

  factor:
    distribution: uniform
    min: 0.1
    max: 0.95

  patience:
    distribution: int_uniform
    min: 0
    max: 2
  # - - -

  # Validate, run sep. tuning for batch size
  batch_size:
    value: 384
  #    values: [ 32, 64, 128, 256, 384 ]

  # Validate, run sep. tuning for freeze
  freeze_epochs:
    value: 3
  #    distribution: int_uniform
  #    min: 0
  #    max: 5


  # - - -
  include_random_grayscale:
    values: [ True ]
  include_random_perspective:
    values: [ True ]
  include_random_erasing:
    values: [ True ]
  include_random_rotation:
    values: [ True ]
  include_center_crop:
    values: [ True ]
  include_random_horizontal_flip:
    values: [ True ]
  include_color_jitter:
    values: [ True ]

  include_random_affine:
    values: [ False ]
  include_gaussian_blur:
    values: [ False ]
  include_gaussian_noise:
    values: [ False ]

count: 50
