# Default config
# i.e. added metrics for:
# Run 1: ACC = X MAE = Y

#https://wandb.ai/qqwy/age_gender_classifier_test/runs/faz3nj4u

# Model configuration
model_type: "mobilenet_v3_small"
num_epochs: 12
freeze_epochs: 1

# Data configuration
batch_size: 128
#ds_path: "dataset/full"
#ds_path: "dataset/fold_2_4_8"
ds_path: "dataset/fold_0_1_2_4_8"

# Optimization parameters
base_lr: 0.008203633726050548
weight_decay: 0.0242358121809478
lr_mult: 9.53764515105303
lr_scheduler: "cosine"
pct_start: 0.3820296456493033

# Task balancing
gender_loss_weight: 0.9

include_random_grayscale: true
include_random_perspective: true
include_random_erasing: true
include_random_rotation: true
include_center_crop: true
include_random_horizontal_flip: true
include_color_jitter: true

include_random_affine: false
include_gaussian_blur: false
include_gaussian_noise: false