

#Model configuration
model_type: "mobilenet_v3_small"
num_epochs: 25
freeze_epochs: 1

# Data configuration
batch_size: 384
#ds_path: "dataset/folds/fold_0"
ds_path: "dataset/fold_0_1_2_4_8"

# Optimizer
base_lr: 0.1
weight_decay: 0.027876325487892428


# Scheduler
lr_scheduler: "reduce_on_plateau"
factor: 0.8
patience: 0
#threshold: -0.075
threshold: 0.05

# Task balancing
gender_loss_weight: 0.9

# Additional transforms
include_color_jitter: true
include_random_erasing: true
include_random_horizontal_flip: true
include_random_rotation: true
include_random_perspective: true
include_center_crop: true
include_random_affine: false
include_random_grayscale: true
include_gaussian_blur: false
include_gaussian_noise: false